### ISSUE TITLE
Problem with magic forms and new latest octobercms build 467

### ISSUE THREAD

**Issue by SplicedWeb** [skydiver/october-plugin-forms#203]
Magic Forms is not compatible with Build 467 (and possibly 466)

Upgrading from Build 465 to 467 caused the component to no longer allow saving settings into the component for genericForm.

For example, when clicking "Security" > "Allowed Fields" when values already existed, you can see the values but cannot remove/change and save. (ok and cancel buttons missing from modal).
[Screenshot](https://www.screencast.com/t/ECV8q76e)

If the field was empty, you can now see html in the modal - but you cannot remove it and save correct values.
[Screenshot](https://www.screencast.com/t/6ijEdQXGejg)

This has happened on two different sites so far, on two different servers
One running php 7.1 another running php 7.3.11

This effectively breaks a sites functionality as forms are potentially disabled/broken/cannot be set up.

**Comment by SplicedWeb** [comment]
This issue occurs on all fields with stringList type defined.

**Comment by skydiver** [comment]
Hello @SplicedWeb 

Thanks for the report.

Will take a look ... stay tuned.

**Comment by mjauvin** [comment]
I confirm the problem.

**Comment by skydiver** [comment]
If you see this image 
![image](https://user-images.githubusercontent.com/578784/88459246-46ecca00-ce6a-11ea-8955-cec46f1836af.png), the html is the footer of the modal.

Need to confirm is an October bug or something else ...

**Comment by SplicedWeb** [comment]
@skydiver thanks, created [issue](https://github.com/octobercms/october/issues/5222)

**Comment by bennothommo** [comment]
@skydiver @SplicedWeb I've pushed https://github.com/octobercms/october/commit/d49266ad90246fcf90565de8ccdcdbad492de0fe which should fix this, and will be out with build 468. If you would like to test the fix, make the change manually in your October CMS install and run `php artisan october:util compile js`, this fix should then be available.

**Comment by mjauvin** [comment]
I confirm this resolves the issue.

Thanks @bennothommo !

**Comment by skydiver** [comment]
thanks @SplicedWeb for flag this and fill that thicket 💪

**Comment by MateThemes** [comment]
Hello!

It is also not possible to add a recipient to the form. It is the same like shown above, you can see HTML in the modal.

The plugin needs a fast fix. 

Thank you very much!

**Comment by skydiver** [comment]
Hey @MateThemes 

We are waiting for October build 468 ... https://octobercms.com/changelog

**Comment by SplicedWeb** [comment]
@MateThemes
You may wish to fix yourself as per the suggestion by @bennothommo

> @skydiver @SplicedWeb I've pushed [octobercms/october@d49266a](https://github.com/octobercms/october/commit/d49266ad90246fcf90565de8ccdcdbad492de0fe) which should fix this, and will be out with build 468. If you would like to test the fix, make the change manually in your October CMS install and run `php artisan october:util compile js`, this fix should then be available.

**Comment by bennothommo** [comment]
@MateThemes @skydiver October 468 has been released as an edge update, but these fixes were not compiled into the combined Storm UI assets before the release. If you update to 468, run `php artisan october:util compile js` afterwards and you'll get the fix. We'll have this resolved properly for 469 which should be the next stable build - apologies for any inconvenience.

**Comment by get-web** [comment]
Solution without compilation:
public_html/modules/system/assets/ui/**storm-min.js**

Search: 
`<textarea class="form-control size-small field-textarea" name="name" value=""/>`
Replace:
`<textarea class="form-control size-small field-textarea" name="name"></textarea>`

![OctoberCMS](https://user-images.githubusercontent.com/39173640/92528403-5e70ee00-f231-11ea-916c-405d2f87a6d4.jpg)

**Comment by mjauvin** [comment]
This has been fixed in latest October edge buikd, v469

**Comment by SplicedWeb** [comment]
> This has been fixed in latest October edge buikd, v469
I'm not sure that it has /modules/system/assets/ui/storm-min.js?v=469 still shows unclosed after update. Is a compile still needed?

Your solution was helpful though, thank you.
